name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'enhance-gh-actions']
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup
        run: |
          npm ci
          npm run build

      - name: Build files
        run: node dist/main.js

      - name: Prepare commit message
        id: prepare_commit_message
        run: |
          TZ=JST-9 date "+%Y-%m-%d %H:%M:%S" | sed 's/.*/COMMIT_MESSAGE="&"/' >> "${GITHUB_OUTPUT}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ steps.prepare_commit_message.outputs.COMMIT_MESSAGE }}
          publish_branch: gh-pages-sandbox # 実装完了後に除却する
          publish_dir: ./output
