name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deno setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.4.x'
          cache: 'true'

      - name: Build files
        run: deno run dev

      - name: Prepare commit message
        id: prepare_commit_message
        run: |
          TZ=JST-9 date "+%Y-%m-%d %H:%M:%S" | sed 's/.*/COMMIT_MESSAGE="&"/' >> "${GITHUB_OUTPUT}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ steps.prepare_commit_message.outputs.COMMIT_MESSAGE }}
          publish_dir: ./output
