name: lint check

on: [ pull_request ]

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deno setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.4.x'
          cache: 'true'

      - name: deno lint
        run: deno lint
